services:
  - type: web
    name: translate-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: SOURCE_CHANNEL_ID
        sync: false
      - key: TARGET_CHANNEL_ID
        sync: false
